export {default as LandingPage} from './landingpage';
export {default as Navbar} from './navbar';
export {default as Footer} from './footer';
export {default as AboutUs} from './aboutUs';
export {default as OurWork} from './ourWork';
export {default as Services} from './services';
export {default as Contact} from './contact';
export {default as Splash} from './splash';
export {default as ParallaxTest} from './parallaxTest.js';